name: Build container image

on:
  pull_request:
    branches: ['main']

jobs:
  build-image:
    strategy:
      matrix:
        image: ['gohugo']
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container image
        uses: docker/build-push-action@44ea916f6c540f9302d50c2b1e5a8dc071f15cdf
        with:
          context: ${{ matrix.image }}
          platforms: linux/amd64,linux/arm64
          push: false
